version: "3"

services:
  app:
    build: .
    volumes:
      - .:/work:cached
      - ./.env.docker:/work/.env:cached
      - target:/work/target:delegated
    depends_on:
      - db
    ports:
      - 5081:80
    command: /bin/sh -c "cargo watch -x run"

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10081:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./db
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  target:
  db-store:
